version: '3.8'
services:
  pg-mech-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      NEXT_PUBLIC_SITE_NAME: ${NEXT_PUBLIC_SITE_NAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - "80:80"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 200M
