version: '3.8'

services:
  pg-mech-app:
    image: pg-mech-app:latest  # Ensure this is the correct image name and tag
    deploy:
      replicas: 1
    ports:
      - "80:80"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      - NEXT_PUBLIC_SITE_NAME=${NEXT_PUBLIC_SITE_NAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    volumes:
      - /data:/app/data  # Example volume mount, adjust as needed
