# fly.toml app configuration file generated for pg-mech-app on 2024-12-15T22:58:37-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pg-mech-demo'
primary_region = 'dfw'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
