name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Navigate to the project directory
          cd ~/pg-mech-app

          # Pull the latest changes
          git pull origin main

          # Create/update .env file
          cat <<EOF > .env
          MONGODB_URI=${{ secrets.MONGODB_CONN_STRING }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
          NEXT_PUBLIC_SITE_NAME=${{ secrets.NEXT_PUBLIC_SITE_NAME }}
          EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          EOF

          # Build the Docker image locally
          sudo docker build -t pg-mech-app:latest .

          # Deploy using Docker Compose
          sudo docker-compose down
          sudo docker-compose up -d --remove-orphans
